name: Run Tests

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install pytest>=7.4.0 pytest-asyncio>=0.21.0 pytest-mock>=3.11.0 pytest-cov>=4.1.0 respx>=0.20.0

    - name: Run tests
      run: |
        python -m pytest tests/ -v --cov=glossary_updater --cov-report=term-missing

    - name: Upload coverage to Codecov
      if: success()
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: false
